version: '3.8'

services:
  app:
    build:
      context: .  # The current directory, where the Dockerfile is located
    ports:
      - "5555"  # Assuming your app runs on port 3000
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13  # You can change the version as needed
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist the database data between container restarts
    networks:
      - app-network
  redis:
    image: redis:alpine  # Use the Redis Alpine image for a smaller footprint
    container_name: redis
    ports:
      - "6379:6379"  # Expose port 6379 for Redis (the default port)
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:3000"  # Expose NGINX on port 3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # NGINX configuration file
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:  
